### ISSUE TITLE
Request: Highlight React components with a unique color

### ISSUE THREAD

**Issue by julian-acosta-alwaysai** [luciascarlet/tailwind-moon-vscode#1]
Love this theme. Hope this is the right place to post this.

It would be great if React components were highlighted in a unique color to easily differentiate between them and standard html/jsx tags

<img width="843" alt="Screen Shot 2021-08-09 at 3 59 59 PM" src="https://user-images.githubusercontent.com/69525966/128784823-c1a7c4dd-cfec-4cd9-a856-3df943ef6edc.png">

**Comment by luciascarlet** [comment]
Yeah, posting here is fine. Good idea actually, having worked with React myself – I based this syntax theme on the Tailwind Breeze syntax originally so all the highlighting is exactly the same as in Tailwind Breeze. As a result, it also only really uses 4 colours for the entire theme, which is part of what makes it so easy on the eyes in the long run in my opinion, but that also means that I'm not really sure what colour I would use for the React components. I feel like blue could work, or I could also change the colour of HTML elements to blue or violet, so the React components are pink which all types are in this theme. I think that would make more sense semantically than having React components be a different colour from other types.

I'm not really sure what I'd do about it not matching Tailwind Breeze though in that case – maybe I'll just fork Breeze too and add it to this theme, as I made my own personal modifications to it, so it may be helpful to publish those as well.

**Comment by luciascarlet** [comment]
Pushing it now! Haven't really used this theme much so I didn't get around to doing it, but in version 2.5, I have changed the syntax highlighting of HTML elements. I should really fork Breeze...

**Comment by julacosta9** [comment]
@luciascarlet Amazing! Just saw the update! Appreciate you following up on this, it looks great!
